### ISSUE TITLE
brew install circos: Can't locate CPAN/Meta.pm

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/homebrew-science#356]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?

#### Brief summary of issue:
Installation of circos cannot find CPAN/Meta.pm even though it is in brewed perl's @INC. Error reports that the installation is using incorrect @INC (see gist-logs).

From gist-logs:
```
Can't locate CPAN/Meta.pm in @INC (@INC contains: /home/linuxbrew/.linuxbrew/Cellar/circos/0.67-7/libexec/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Build.PL line 15.
BEGIN failed--compilation aborted at Build.PL line 15.
```
```
$ which perl
/home/linuxbrew/.linuxbrew/bin/perl
```
```
$ perl -e 'print join("\n",@INC)'
/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi
/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/site_perl/5.26.1
/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1/x86_64-linux-thread-multi
/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1
/home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi
/home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.26.1
```
```
$ ls /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1/CPAN/Meta.pm
/home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/lib/perl5/5.26.1/CPAN/Meta.pm
```
#### The complete command that you issued:
Both of the following result in the same error:
see first gist-logs for:
```
$ brew install circos
```
and
see second gist-logs for:
```
$ export PERL="/home/linuxbrew/.linuxbrew/bin/perl"
$ brew install circos
```
#### Gist with output of `brew doctor`:
```
$ brew dr
Your system is ready to brew.
```
#### Link output by `brew gist-logs <formula>`:
https://gist.github.com/jwhite007/91ccb3dd7b0cb8aee6ae433d9561262f
https://gist.github.com/jwhite007/a340c90d49d6127999b884fbfa6d7416
#### Output of `brew config`:
```
$ brew config
HOMEBREW_VERSION: 1.3.7-14511-gfbc16c2
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: fbc16c2b5b62baea3e63bac5bf2e82f1e75126df
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: cde85c35f1d876f621f1ae8d7b1edf37f64681e2
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/linuxbrew/.cache
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GIT_CONFIG_FILE: /home/linuxbrew/.linuxbrew/Homebrew/.git/config
HOMEBREW_LOGS: /home/linuxbrew/.logs
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_TEMP: /home/linuxbrew/.temp
HOMEBREW_VISUAL: /usr/bin/vim
CPU: octa-core 64-bit merom
Homebrew Ruby: 2.4.2 => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/bin/ruby
Clang: N/A
Git: 2.15.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.56.1 => /home/linuxbrew/.linuxbrew/opt/curl/bin/curl
Perl: /home/linuxbrew/.linuxbrew/bin/perl => /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.14/bin/python2.7
Ruby: /home/linuxbrew/.linuxbrew/bin/ruby => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.2_1/bin/ruby
Java: 9.0.1
Kernel: Linux 2.6.32-504.el6.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 6.6 (Santiago) (Santiago)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: 2.23
gcc: 5.4.0
xorg: 20170115
```

**Comment by sjackman** [comment]
It looks like maybe it's using `/usr/bin/perl` or `/usr/local/bin/perl` rather than the brewed version of `perl`. As an experiment, can you please try editing the `circos` formula with `brew edit circos` and adding the line:
```ruby
depends_on :perl => "5.26"
```
and if that doesn't work, try…
```ruby
depends_on "perl"
```

**Comment by jwhite007** [comment]
Thanks so much Shaun. ```depends_on :perl => "5.26"``` did it!
